import LayersIcon from '@mui/icons-material/LayersOutlined';
import PublicIcon from '@mui/icons-material/PublicOutlined';
import BusinessIcon from '@mui/icons-material/BusinessOutlined';
import PersonIcon from '@mui/icons-material/PersonOutlined';

export const availabilityCategories = {
    all: { label: 'All', icon: LayersIcon },
    public: { label: 'Public', icon: PublicIcon },
    organisation: { label: 'Organisation', icon: BusinessIcon },
    personal: { label: 'Personal', icon: PersonIcon }
};

const boreholeLayerDef = {
    id: "boreholes",
    name: "Boreholes",
    geometryType: "Point",
    visibleByDefault: true,
    symbology: {
        type: "circle",
        color: "#1f78b4",
        radius: 6,
        borderColor: "#000000",
        borderWidth: 1
    },
    attributes: [
        {
            id: "id",
            name: "Borehole ID",
            type: "string",
            required: true,
            autoGenerated: true
        },
        {
            id: "borehold_ref",
            name: "Borehole Reference",
            type: "string",
            required: false
        },
        {
            id: "depth",
            name: "Depth (m)",
            type: "number",
            required: false,
            min: 0
        },
        {
            id: "groundwater",
            name: "Groundwater Depth (m)",
            type: "number",
            required: false
        },
        {
            id: "date",
            name: "Investigation Date",
            type: "date",
            required: false
        },
        {
            id: "drilling_method",
            name: "Drilling Method",
            type: "enum",
            options: ["Cable Percussion", "Rotary", "Window Sampler", "Other"],
            required: false
        },
        {
            id: "log",
            name: "Borehole Log (PDF)",
            type: "file",
            required: true
        }
    ]
};

export const defaultLayer = [boreholeLayerDef]